# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

FROM quay.io/fedora/fedora:latest

RUN dnf install -y \
        cargo \
        cpio \
        dnf5-plugins \
        erofs-utils \
        gcc \
        gh \
        git \
        jq \
        just \
        openssl-devel \
        podman \
        wget \
    && \
    dnf clean all
