FROM quay.io/fedora/fedora:latest

RUN dnf install -y \
        cargo \
        cpio \
        dnf5-plugins \
        erofs-utils \
        gcc \
        git \
        jq \
        just \
        openssl-devel \
        podman \
        wget \
    && \
    dnf config-manager addrepo --from-repofile="https://cli.github.com/packages/rpm/gh-cli.repo" \
    && \
    dnf install -y gh --repo gh-cli \
    && \
    dnf clean all
