# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name := "sysexts-manager"
files := "usr"
upholds := "
sysexts-manager.service
"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import 'sysext.just'

all: default

# Will be set in CI
version:
    echo "0.3.0" > ./version
